version: "3.9"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/logs:/var/log/nginx"
    depends_on:
      - app
  
  db:
    image: "mysql:latest"
    env_file:
      - "./mysql/.env"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/logs:/var/log/mysql"
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    volumes:
      - "./app/logs/:/app/logs/"
    depends_on:
      - "db"